# Generated by Django 3.2.3 on 2023-01-12 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ImageField(default='images/profile.jpg', upload_to='images')),
                ('name', models.CharField(max_length=100, null=True)),
                ('dob', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('acc_number', models.CharField(max_length=15, null=True)),
                ('curr_balance', models.IntegerField(default=0)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransferDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=100, null=True)),
                ('receiver_name', models.CharField(max_length=100, null=True)),
                ('amount', models.IntegerField(default=0)),
                ('trans_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
